### PR TITLE
Wait for screenshots to finish before generating the video

### LINKED ISSUE #40: The latest screenshots do not fall within the ffmpeg video.
When I'm using wdio-video-reporter library, the latest two screenshots do not fall within the ffmpeg video. 
**BTW** all screenshots are saved at the _results_ folder but there are no two latest in the ffmpeg video. 

**Log**
The log is empty after I set `wdio.config.logLevel = 'debug'`.. **But**, please see the following log from my test result:

```
[0-0] PASSED in chrome - /src/test/Welcome.test.js
2020-04-06T10:20:45.942Z INFO @wdio/cli:launcher: Run onComplete hook
 "Video" Reporter:
Using reporter config:[
  [
    null,
    {
      "saveAllVideos": true,
      "videoSlowdownMultiplier": 3
    }
  ],
  [
    "allure",
    {
      "outputDir": "./allure-results",
      "disableWebdriverStepsReporting": true,
      "disableWebdriverScreenshotsReporting": true,
      "disableMochaHooks": true
    }
  ]
]
Using config:{
  "debugMode": true,
  "logLevel": "info",
  "videoRenderTimeout": 5,
  "outputDir": "_results_",
  "allureOutputDir": "/Users/maks-pc/IdeaProjects/Oji/ui-tests/allure-results",
  "rawPath": "rawSeleniumVideoGrabs",
  "usingAllure": true,
  "saveAllVideos": true,
  "videoSlowdownMultiplier": 3,
  "excludedActions": [],
  "jsonWireActions": [
    "url",
    "forward",
    "back",
    "refresh",
    "execute",
    "size",
    "position",
    "maximize",
    "click",
    "submit",
    "value",
    "keys",
    "clear",
    "selected",
    "enabled",
    "displayed",
    "orientation",
    "alert_text",
    "accept_alert",
    "dismiss_alert",
    "moveto",
    "buttondown",
    "buttonup",
    "doubleclick",
    "down",
    "up",
    "move",
    "scroll",
    "doubleclick",
    "longclick",
    "flick",
    "location"
  ]
}
--- New suite: LoginTests ---
--- New test: userShouldBeLogin ---
Incomming command: /session/:sessionId/url => [url]
- Screenshot!!
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/element => [element]
Incomming command: /session/:sessionId/element/0.7028752295507747-1/clear => [clear]
- Screenshot!!
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/element/0.7028752295507747-1/value => [value]
- Screenshot!!
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/element => [element]
Incomming command: /session/:sessionId/element/0.7028752295507747-2/clear => [clear]
- Screenshot!!
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/element/0.7028752295507747-2/value => [value]
- Screenshot!!
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/element => [element]
Incomming command: /session/:sessionId/element/0.7028752295507747-3/click => [click]
- Screenshot!!
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/element => [element]
Incomming command: /session/:sessionId/elements => [elements]
Incomming command: /session/:sessionId/elements => [elements]
Incomming command: /session/:sessionId/elements => [elements]
Incomming command: /session/:sessionId/element => [element]
Incomming command: /session/:sessionId/element/0.7028752295507747-4/click => [click]
- Screenshot!!
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/element => [element]
Incomming command: /session/:sessionId/element/0.7028752295507747-5/click => [click]
- Screenshot!!
- Screenshot!!
ffmpeg command: "/Users/maks-pc/IdeaProjects/Oji/ui-tests/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg" -y,-r,10,-i,"/Users/maks-pc/IdeaProjects/Oji/ui-tests/_results_/rawSeleniumVideoGrabs/LoginTests--userShouldBeLogin--CHROME--04-06-2020--13-20-38-604/%04d.png",-vcodec,libx264,-crf,32,-pix_fmt,yuv420p,-vf,"scale=1200:trunc(ow/a/2)*2","setpts=3.0*PTS","/Users/maks-pc/IdeaProjects/Oji/ui-tests/_results_/LoginTests--userShouldBeLogin--CHROME--04-06-2020--13-20-38-604.mp4"
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId/screenshot => [screenshot]
Incomming command: /session/:sessionId => [:sessionId]
--- FFMPEG is done ---
Generated:[
  "/Users/maks-pc/IdeaProjects/Oji/ui-tests/_results_/LoginTests--userShouldBeLogin--CHROME--04-06-2020--13-20-38-604.mp4"
]
Video reporter Done!
Spec Files:      1 passed, 1 total (100% completed) in 00:00:09 
2020-04-06T10:20:45.946Z INFO @wdio/local-runner: Shutting down spawned worker
2020-04-06T10:20:46.200Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-04-06T10:20:46.201Z INFO @wdio/local-runner: shutting down
```

**Expected behavior**
The latest screenshots should be added to the video.

**Environment:**
 - **wdio-video-reporter version:** [2.0.0]
 - **WebdriverIO version:** [5.7.15]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [10.12.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [Chrome 71]
 - **Platform name and version:** [MacOs Catalina]

**Desktop:**
 - OS: [MacOs 10.15.4]
 - Browser [chrome]
 - Version [80.0.3987.149]

I see that the ffmpeg command is executed before the two latest screenshots...

### PR DESCRIPTION
**Pull request by joaquimds**
To fix #40. `browser.saveScreenshot()` returns a promise, so sometimes the video generation would begin before all screenshots were saved. This can be fixed by storing `this.screenshotPromises`, in the same way that `this.videoPromises` is stored, and waiting for them to complete before initializing the ffmpeg child process.

I needed to return the promise from helpers.generateVideo(), so that the tests could wait for it to complete before making their assertions. This is because adding another promise to the chain - `Promise.all(this.screenshotPromises)` - prevents the function from executing synchronously.

### CODE REVIEW

**Comment by presidenten** [comment]
Sorry, I just wrapped up a couple of certification exams, and now Im on vacation. Ill check it out when I get back.

**Comment by presidenten** [comment]
Sorry for the long wait. Finally back after 2 months of much needed vacation :-)

I finally had a look at the PR properly and its really nice. Huge thanks for this fix!

**Comment by presidenten** [comment]
There is another PR that will be merged soon. Ill make a release as soon as it is merged or within a week or so.

**Comment by presidenten** [comment]
Now available in v3.1.0

**Comment by joaquimds** [comment]
Awesome! I just got back from holiday myself! Thanks so much 😊

**Pull request merged**
