### PR TITLE
Enhancement: Upgrade package to support for WebdriverIO v6

### LINKED ISSUE #43: Extend wdio-video-reporter to support WebdriverIO v6
**Is your feature request related to a problem? Please describe.**
The `wdio-video-reporter` npm package made video recording of test runs nearly seamless with WebdriverIO v5. Because of how useful recording of tests can prove to be, an extension to support WebdriverIO v6 should not be a bad consideration more so because of the fact that this is the only plugin that supports video recording for WebdriverIO v6.

**Describe the solution you'd like**
A start can be with upgrading `@wdio/reporter` npm package to the latest version.

### PR DESCRIPTION
**Pull request by und3fined-v01d**
Upgraded NPM packages:

- @wdio/allure-reporter 5.x -> 6.x
- @wdio/reporter 5.x -> 6.x

New NPM packages:

- @wdio/cli (peer dependency of
@wdio/allure-reporter)

Closes #43

### CODE REVIEW

**Comment by und3fined-v01d** [comment]
Hey @presidenten would it be possible for you to review this PR. It works fine but I'd love to work on any changes that you might have in mind

**Comment by presidenten** [comment]
Yes, Ill try to have a look later during the week. Still alot to do at work.
In the mean time, could you try to sync with the current master branch since there seems to be some conflicts.

**Comment by und3fined-v01d** [comment]
> Yes, Ill try to have a look later during the week. Still alot to do at work.
> In the mean time, could you try to sync with the current master branch since there seems to be some conflicts.

Oh yess I noticed them...we actually both put the code to handle the new popup...Ill try to rebase over the master and commit

**Comment by presidenten** [comment]
I will release this as v3.0.0 as it might have breaking changes with wdio v5

**Comment by presidenten** [comment]
Thanks for the help!

**Comment by presidenten** [comment]
Release:
https://github.com/presidenten/wdio-video-reporter/releases/tag/v3.0.0

**Pull request merged**
