### PR TITLE
Add new option to record all json-wire actions and fix error when no json-wire action is present

### PR DESCRIPTION
**Pull request by und3fined-v01d**
Enhancement: Add option to record all json-wire actions

Bug-fixes: Fix error when no jsonWire endpoint is present

Fixes: #45

### CODE REVIEW

**Comment by und3fined-v01d** [comment]
Hey @presidenten , would it be possible for you to review this 😄?

**Comment by presidenten** [comment]
Sorry, I just wrapped up a couple of certification exams, and now Im on vacation. Ill check it out when I get back.

**Comment by und3fined-v01d** [comment]
Hey @presidenten just checking if you are back from vacation ;-)

**Comment by presidenten** [comment]
Im away on a long vacation this year. Ill be back the 24th of August.
Sorry for the inconvenience...

**Comment by presidenten** [comment]
Sorry for the long wait. Finally back after 2 months of much needed vacation :-)
The code looks good. What is missing in the PR is a mention in the readme as well as full coverage of unit tests. 
Fix those and Ill merge. Now Im back behind a computer, so I can fix it kind of quickly and bundle it for a new release.

**Comment by presidenten** [comment]
You know what? Your issue was super duper nice. So Ill fix the tests and update the readme.

**Comment by presidenten** [comment]
Now available in v3.1.0

**Comment by und3fined-v01d** [comment]
> You know what? Your issue was written super duper nice. So Ill fix the tests and update the readme.

I am glad you're back...hope you had fun in your vacation. This was so sweet of you. Thank you so much 😄

**Pull request merged**
